M48
; DRILL file {KiCad 7.0.8} date Sat Oct  7 13:31:31 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-07T13:31:31+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0630
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0827
%
G90
G05
T1
X4.3016Y-3.1
X4.4Y-3.1
X5.3Y-2.9
X5.3Y-2.9984
X5.5Y-2.9
X5.5Y-3.3
T2
X5.2Y-3.4
X5.3Y-3.4
T3
X4.7Y-2.9
X4.8Y-2.9
X4.9Y-2.9
T4
X3.9177Y-2.95
X3.9177Y-3.25
X5.8Y-2.95
X5.8Y-3.25
T5
X4.5638Y-3.4
X4.8Y-3.4
T0
M30
